apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-admin
subjects:
- kind: User
  name: placeholder_iam_user
  apiGroup: rbac.authorization.k8s.io