apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-backend
  labels:
    app: payment-service-backend
spec:
  selector:
    matchLabels:
      app: payment-service-backend
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      name: payment-service-backend
      labels:
        app: payment-service-backend
    spec:
      containers:
        - name: payment-service-backend
          image: placeholder_repository_name
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /payments/quantity
              port: 8080
            periodSeconds: 60
            failureThreshold: 3
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /payments/quantity
              port: 8080
            periodSeconds: 20
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 8m
            limits:
              cpu: 8m
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: configmap-payment-service-backend
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-payment-service-backend
                  key: POSTGRES_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-payment-service-backend
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-payment-service-backend
                  key: POSTGRES_PASSWORD
            - name: PAYMENT_SUCCESS_SNS_TOPIC_ARN
              valueFrom:
                configMapKeyRef:
                  name: configmap-payment-service-backend
                  key: PAYMENT_SUCCESS_SNS_TOPIC_ARN
            - name: PAYMENT_FAILURE_SNS_TOPIC_ARN
              valueFrom:
                configMapKeyRef:
                  name: configmap-payment-service-backend
                  key: PAYMENT_FAILURE_SNS_TOPIC_ARN