apiVersion: v1
kind: Secret
metadata:
  name: secret-payment-service-backend
type: Opaque
stringData:
  POSTGRES_USER: aws_ssm_db_username
  POSTGRES_PASSWORD: aws_ssm_db_password
  AWS_ACCESS_KEY_ID: aws_access_key_id
  AWS_SECRET_ACCESS_KEY: aws_secret_access_key
