// Code generated by mockery v2.43.2. DO NOT EDIT.

package get_all_payments

import mock "github.com/stretchr/testify/mock"

// MockGetAllPaymentsInterface is an autogenerated mock type for the GetAllPaymentsInterface type
type MockGetAllPaymentsInterface struct {
	mock.Mock
}

// ExecuteGetAllPayments provides a mock function with given fields:
func (_m *MockGetAllPaymentsInterface) ExecuteGetAllPayments() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExecuteGetAllPayments")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGetAllPaymentsInterface creates a new instance of MockGetAllPaymentsInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetAllPaymentsInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetAllPaymentsInterface {
	mock := &MockGetAllPaymentsInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
