// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entities "github.com/CAVAh/api-tech-challenge/src/core/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// OrderInterface is an autogenerated mock type for the OrderInterface type
type OrderInterface struct {
	mock.Mock
}

// GetOrder provides a mock function with given fields: orderId
func (_m *OrderInterface) GetOrder(orderId uint) (*entities.Order, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.Order, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.Order); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotifyStatusChange provides a mock function with given fields: orderId
func (_m *OrderInterface) NotifyStatusChange(orderId uint) (*entities.Order, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for NotifyStatusChange")
	}

	var r0 *entities.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.Order, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.Order); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderInterface creates a new instance of OrderInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderInterface {
	mock := &OrderInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
