// Code generated by mockery v2.43.2. DO NOT EDIT.

package gateways

import (
	entities "github.com/CAVAh/api-tech-challenge/src/core/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentInterface is an autogenerated mock type for the PaymentInterface type
type MockPaymentInterface struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: order
func (_m *MockPaymentInterface) CreatePayment(order entities.Order) (string, error) {
	ret := _m.Called(order)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(entities.Order) (string, error)); ok {
		return rf(order)
	}
	if rf, ok := ret.Get(0).(func(entities.Order) string); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(entities.Order) error); ok {
		r1 = rf(order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockPaymentInterface creates a new instance of MockPaymentInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentInterface {
	mock := &MockPaymentInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
